### ISSUE TITLE
How do i call this package in my google colab?

### ISSUE THREAD

**Issue by AlfredLTennyson** [axelroques/Eye_Movement_Classification#1]
Hey,how do i call this package in my google colab?

Thanks a ton!

**Comment by axelroques** [comment]
Hi, I am not sure how to do that exactly, but I you might find some answers here: https://stackoverflow.com/questions/50850216/google-colab-install-from-github-glrm

**Comment by AlfredLTennyson** [comment]
Okay. Let me try once. 
Thanks a ton!

**Comment by AlfredLTennyson** [comment]
How did you call nslr hmm in your ipynb demo?

**Comment by axelroques** [comment]
I'm not sure I understand your question, the code in [the notebook](https://github.com/axelroques/Eye_Movement_Classification/blob/master/classification.ipynb) is rather self-explanatory:
`
classifier = NSLR_HMM(t, x, y, optimize_noise=False)
`
`
classifier.process()
`
